version: "3"

services:
  suno-api:
    build:
      context: ./apps/suno-api
      args:
        SUNO_COOKIE: ${SUNO_COOKIE}
    volumes:
      - ./public:/app/public
    ports:
      - "3000:3000"

  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
