version: "3"

services:
  suno-api:
    build:
      context: ./apps/suno-api
      args:
        SUNO_COOKIE: ${SUNO_COOKIE}

  orchestrator:
    build:
      context: ./apps/orchestrator
    volumes:
      - ./temp:/app/temp
      - ./videos:/app/videos
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
